vti_encoding:SR|utf8-nl
vti_author:SR|MICHAELLAWR9EFD\\michaellawrence
vti_modifiedby:SR|MICHAELLAWR9EFD\\michaellawrence
vti_timelastmodified:TR|30 Nov 2013 20:33:20 -0000
vti_timecreated:TR|30 Nov 2013 20:24:43 -0000
vti_title:SR|Untitled 1
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|30 Nov 2013 20:25:41 -0000
vti_syncwith_198.83.120.96\:80/fa13/et_718_d1/mlawrence78:TX|30 Nov 2013 20:33:20 -0000
vti_syncofs_198.83.120.96\:80/fa13/et_718_d1/mlawrence78:TW|30 Nov 2013 20:33:01 -0000
vti_cacheddtm:TX|30 Nov 2013 20:33:20 -0000
vti_filesize:IR|758
