<HTML>

<HEAD>

<TITLE>MidiCart PHP</TITLE>
  
</HEAD>

   <FRAMESET ROWS="110,50%" BORDER=0 FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0>
      <FRAME SRC="top.php" NAME=top NORESIZE SCROLLING=no MARGINWIDTH=0 MARGINHEIGHT=0 FRAMEBORDER=0>
      <FRAMESET ROWS="36,50%" BORDER=0 FRAMEBORDER=0>
         <FRAMESET COLS="170,100%" BORDER=0 FRAMEBORDER=0>
            <FRAME SRC="middle_left.php" NAME="cart" NORESIZE SCROLLING=no MARGINWIDTH=0 MARGINHEIGHT=12 BORDER=0 FRAMEBORDER=0>
            <FRAME SRC="empty.php" NAME="middle_right" SCROLLING=no MARGINWIDTH=10 MARGINHEIGHT=2 FRAMEBORDER=0>
         </FRAMESET>
         <FRAMESET COLS="170" BORDER=0 FRAMEBORDER=0>
            
          
 	<!--		<FRAME SRC="categories.php" NAME=categories NORESIZE MARGINWIDTH=6 MARGINHEIGHT=11 FRAMEBORDER=0> -->
            <FRAME SRC="main.php" NAME=main MARGINWIDTH=10 MARGINHEIGHT=4 FRAMEBORDER=0>
         </FRAMESET>
      </FRAMESET>
   </FRAMESET>

</HTML>

        <!--    <FRAME SRC="categories.php" NAME="cart" NORESIZE SCROLLING=no MARGINWIDTH=0 MARGINHEIGHT=12 BORDER=0 FRAMEBORDER=0> -->
